#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    echo "no commit hash given. abort." >&2
    exit 1
fi

tree_url="$(gh browse --branch $1 --no-browser)"
commit_url="${tree_url/tree/commit}"

if [ -n "$GH_BROWSER" ]; then
    eval "$GH_BROWSER \"$commit_url\""
    exit $?
fi

if [ -n "$BROWSER" ]; then
    eval "$BROWSER \"$commit_url\""
    exit $?
fi

open "$commit_url"
exit $?
