#!/usr/bin/env python

# 1st
import os
import sys

# 2nd
import vake

# change to script's directory
os.chdir(
    vake.pilot(__file__).abspath().parent().pathname()
)

# run application
vake.cli().run(sys.argv[1:])
