#!/usr/bin/env python3
import os
import pathlib
import sys

import vake

if sys.hexversion < 0x3090000:
    sys.exit('python 3.9 or newer is required')

os.chdir(pathlib.Path(__file__).parent)

vake.run(sys.argv[1:])
