setopt nonomatch

if [ -f $HOME/.sh.d/shrc ]; then
  . $HOME/.sh.d/shrc
fi
if [ -f /etc/zshrc ]; then
  . /etc/zshrc
fi
for conf in `ls -d $HOME/.zsh.d/*.zshrc`; do
  . $conf
done

# vim: ft=zsh sw=2 ts=2 sts=2
