[colors]
black           = "#000000"
red             = "#ea3e24"
green           = "#5cc93b"
yellow          = "#c6c43d"
blue            = "#4ea5f8"
magenta         = "#e933f6"
cyan            = "#68e1e5"
white           = "#c7c7c7"
light-black     = "#676767"
light-red       = "#ef766d"
light-green     = "#8cf67a"
light-yellow    = "#fefb7e"
light-blue      = "#6a71f6"
light-magenta   = "#f07ef8"
light-cyan      = "#6af5f6"
light-white     = "#6af5f6"

background      = "#0c0c0c"
foreground      = "#d9d9d9"
cursor          = "#ffffff"
