[colors]
black           = "<%= it[0] %>"
red             = "<%= it[1] %>"
green           = "<%= it[2] %>"
yellow          = "<%= it[3] %>"
blue            = "<%= it[4] %>"
magenta         = "<%= it[5] %>"
cyan            = "<%= it[6] %>"
white           = "<%= it[7] %>"
light-black     = "<%= it[8] %>"
light-red       = "<%= it[9] %>"
light-green     = "<%= it[10] %>"
light-yellow    = "<%= it[11] %>"
light-blue      = "<%= it[12] %>"
light-magenta   = "<%= it[13] %>"
light-cyan      = "<%= it[14] %>"
light-white     = "<%= it[15] %>"

background      = "#0c0c0c"
foreground      = "#d9d9d9"
cursor          = "#ffffff"
