format = """${username}@${hostname}: ${directory} ${status}
% """

right_format = "[\\[$git_branch\\]](purple)"

add_newline = false

[username]
format = '[$user]($style)'
style_user = 'cyan'
style_root = 'red bold'
disabled = false
show_always = true

[hostname]
format = '[$hostname]($style)'
style = 'cyan'
disabled = false
ssh_only = false

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'
style = 'yellow'
disabled = false
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = '[$branch(:$remote_branch)]($style)'
style = 'none'
disabled = false

[status]
format = "[\\[$status\\]]($style)"
style = "bold red"
disabled = false
